-- ─────────────────────────────────────────────────────────
-- GBC Analytics Dashboard — Supabase Schema
-- Run this in: Supabase Dashboard → SQL Editor → New query
-- ─────────────────────────────────────────────────────────

-- 1. Orders table
CREATE TABLE IF NOT EXISTS orders (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        TEXT NOT NULL UNIQUE,                       -- e.g. "ORD-001" or externalId
  customer_name   TEXT,
  customer_phone  TEXT,
  customer_email  TEXT,
  city            TEXT NOT NULL,
  total_amount    NUMERIC(12, 2) NOT NULL DEFAULT 0,           -- sum(quantity * initialPrice)
  utm_source      TEXT,                                        -- instagram | google | tiktok | direct | referral
  status          TEXT NOT NULL DEFAULT 'new',
  created_at      TIMESTAMPTZ NOT NULL,
  raw_data        JSONB,                                       -- full order JSON from RetailCRM
  synced_at       TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Index for dashboard queries
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders (created_at);
CREATE INDEX IF NOT EXISTS idx_orders_utm_source ON orders (utm_source);
CREATE INDEX IF NOT EXISTS idx_orders_city ON orders (city);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_order_id ON orders (order_id);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- 4. Allow public read-only access for the dashboard
CREATE POLICY "Allow public read" ON orders
  FOR SELECT USING (true);

-- 5. Allow service role full access (used by sync script)
CREATE POLICY "Allow service role all" ON orders
  FOR ALL USING (auth.role() = 'service_role');
