-- ─────────────────────────────────────────────────────────
-- GBC Analytics Dashboard — Supabase Schema
-- Run this in: Supabase Dashboard → SQL Editor → New query
-- ─────────────────────────────────────────────────────────

-- 1. Orders table (если ещё не создана)
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT NOT NULL UNIQUE,
  customer_name TEXT,
  customer_phone TEXT,
  customer_email TEXT,
  city TEXT NOT NULL,
  total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  utm_source TEXT,
  status TEXT NOT NULL DEFAULT 'new',
  created_at TIMESTAMPTZ NOT NULL,
  raw_data JSONB,
  synced_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Indexes (если ещё не созданы)
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders (created_at);
CREATE INDEX IF NOT EXISTS idx_orders_utm_source ON orders (utm_source);
CREATE INDEX IF NOT EXISTS idx_orders_city ON orders (city);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_order_id ON orders (order_id);

-- 3. RLS (только если ещё не включен)
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- 4. Политики (проверяем существование перед созданием)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read' AND tablename = 'orders') THEN
    CREATE POLICY "Allow public read" ON orders FOR SELECT USING (true);
  END IF;
END $$;
